[pytest]
addopts = -p no:cacheprovider
filterwarnings =
    ignore:'asyncio.iscoroutinefunction' is deprecated.*:DeprecationWarning:fastapi.routing
    ignore:'asyncio.iscoroutinefunction' is deprecated.*:DeprecationWarning:starlette._utils
    ignore:websockets.legacy is deprecated.*:DeprecationWarning:websockets.legacy
    ignore:The 'app' shortcut is now deprecated.*:DeprecationWarning:httpx._client
